In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../../data/checkpoint.csv')
df.head()

   idx         lng        lat    hdong_code hdong_name        b_code
0    1  126.961305  37.552684  1.144056e+09        공덕동  1.144010e+09
1   15  126.900435  37.524457  1.156055e+09       당산1동  1.156011e+09
2   31  126.858754  37.520246  1.147062e+09       신정1동  1.147010e+09
3   32  126.838704  37.526693  1.147056e+09       신월1동  1.147010e+09
4   33  126.867719  37.541744  1.147053e+09        목3동  1.147010e+09

In [3]:
len(df)

110359

In [ ]:
import pandas as pd

cols = ['대지위치', '법정동코드명', '주용도코드명', '기타용도내용',
        '사용승인일자', '대지면적', '세대수']

df_원본 = pd.read_csv('../../data/서울시 건축물대장 표제부.csv',
                      encoding='cp949',
                      encoding_errors='ignore',
                      on_bad_lines='skip',
                      usecols=cols)


df_원본.head()

                   대지위치 법정동코드명   대지면적     주용도코드명   기타용도내용   세대수      사용승인일자
0  서울특별시 강서구 방화동 246-66    방화동  274.0       단독주택  주택 및 창고   NaN  1989-06-30
1  서울특별시 마포구 아현동 751-11    아현동    0.0       공동주택     연립주택   6.0  1984-08-06
2   서울특별시 양천구 신월동 987-1    신월동    0.0       공동주택      아파트  96.0  1988-04-30
3   서울특별시 양천구 신정동 87-39    신정동    0.0  제1종근린생활시설   근린생활시설   0.0  1990-12-29
4  서울특별시 강서구 화곡동 102-29    화곡동  172.9       단독주택     단독주택   0.0  1990-08-18

In [6]:
len(df_원본)

593048

In [8]:
print(df_원본['주용도코드명'].value_counts())
# 또는 용도코드 컬럼명이 다를 수 있으니
print(df_원본.columns.tolist())

주용도코드명
단독주택          290155
공동주택          141801
제2종근린생활시설      63319
제1종근린생활시설      57877
업무시설           10288
교육연구시설          8256
노유자시설           3250
종교시설            2954
공장              2356
숙박시설            1988
자동차관련시설         1888
창고시설            1583
문화및집회시설         1421
판매시설            1225
근린생활시설           959
의료시설             799
위험물저장및처리시설       668
운동시설             355
교정및군사시설          290
운수시설             268
관광휴게시설           182
교육연구및복지시설        170
동물및식물관련시설        170
위락시설             167
분뇨.쓰레기처리시설       142
방송통신시설            94
국방,군사시설           93
자원순환관련시설          77
수련시설              73
묘지관련시설            47
판매및영업시설           41
발전시설              23
공공용시설             12
야영장시설             10
장례시설               6
다가구주택              2
가설건축물              1
교정시설               1
Name: count, dtype: int64
['대지위치', '법정동코드명', '대지면적', '주용도코드명', '기타용도내용', '세대수', '사용승인일자']

In [9]:
# 단독·다가구 건물 수 확인
단독 = df_원본[df_원본['기타용도내용'].str.contains('단독주택|다가구', na=False)]
print(f"단독·다가구: {len(단독)}개")

# 이미 매핑된 연립·다세대
연립다세대 = df_원본[df_원본['기타용도내용'].str.contains('연립주택|다세대주택', na=False)]
print(f"연립·다세대: {len(연립다세대)}개")

# 추가로 API 돌려야 할 건물 수
print(f"추가 필요: {len(단독) - (99722 - len(연립다세대))}개 대략")

단독·다가구: 153198개
연립·다세대: 73745개
추가 필요: 127221개 대략